USE customer_behavior;

SELECT * 
FROM customer;

-- Q1 What is the total revenue generated by Male customers Vs Female customers?
SELECT 
	gender,
    SUM(purchase_amount) AS Revenue
FROM customer
GROUP BY gender
ORDER BY Revenue DESC;

-- Q2 Which customers used the discount yet spent more than the average purchase amount?
SELECT 
	customer_id,
    AVG(purchase_amount) AS avg_purchase_amnt
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (
		SELECT AVG(purchase_amount) AS avg_purchase_amount
		FROM customer
)
GROUP BY customer_id;

-- Q3 What are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_review
FROM customer
GROUP BY item_purchased
ORDER BY avg_review DESC
LIMIT 5;

-- Q4 Compare the average purchase amounts between the standard & express shipping
SELECT 
	shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amnt
FROM customer
WHERE shipping_type IN ('Standard', 'Express') -- shipping_type = 'Standard' OR shipping_type = 'Express'
GROUP BY shipping_type;

-- Q5 Do subscribed customers spend more? 
-- Compare average spent and total revenue between subscribers and non-subscribers
SELECT 
    subscription_status,
    COUNT(customer_id) AS customer_nos,
    AVG(purchase_amount) AS avg_spent,
    SUM(purchase_amount) AS total_revenue
FROM customer
WHERE subscription_status IN ('Yes', 'No')
GROUP BY subscription_status;

-- Q6 What are the top 5 products that have highest percentage of purchases with discounts applied?
SELECT 
	item_purchased,
    ROUND(((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)) * 100) / count(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7 Segment customers into New, Returning and Loyal based on their total number of previous purchases
-- and show the count of each segment
WITH customer_type AS(
SELECT 
	customer_id,
    previous_purchases,
    CASE 
		WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
        END AS customer_segment
FROM customer
)
SELECT customer_segment,
COUNT(*) AS customer_total
FROM customer_type
GROUP BY customer_segment;

-- Q8 What are the top 3 frequently purchased products under each category?
WITH item_count as (
SELECT 
	category,
    item_purchased,
    COUNT(customer_id) AS total_orders,
    ROW_NUMBER() OVER(
		PARTITION BY category 
        ORDER BY COUNT(customer_id) DESC
	)AS item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT
    item_rank,
	category,
    item_purchased,
    total_orders
FROM item_count
WHERE item_rank<= 3;

-- Q9 Some customers buy products repeatedly who have more than 5 previous purchases, have they been subscribers?
SELECT 
	subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases >= 5
GROUP BY subscription_status;

-- Q10 What is the revenue contribution of each age group?
SELECT 
	age_group,
	SUM(purchase_amount) AS revenue_contribution
FROM customer
GROUP BY age_group
ORDER BY revenue_contribution DESC;
    
